services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:1917151311@db:5432/KindergartenMealTrackerDatabase
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1917151311
      - POSTGRES_DB=KindergartenMealTrackerDatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d KindergartenMealTrackerDatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    command: redis-server --port 6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:1917151311@db:5432/KindergartenMealTrackerDatabase
      - CELERY_BROKER_URL=redis://redis:6379/0  # Use 'redis' service name
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Use 'redis' service name
    healthcheck:
      test: [ "CMD", "celery", "-A", "app.celery_app", "inspect", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data: